### ISSUE TITLE
Can we have a install/how to run guide?

### ISSUE THREAD

**Issue by sk1418** [R3l3ntl3ss/Clips#11]
Hi,
I am looking for a "self-hosted" kindle clips service.  When I see Clips' animation, I think it almost fits all my needs.
 I cloned your repo.  However, I'm not a javascript developer.
After some googling, I know that I need first to install a js package manager npm/yarn. 
However, after that, both `npm install` and `yarn install` run with errors.
Could you please add a "how to start" section (or something like that) in your readme.md? 
Thank you.

**Comment by D3vd** [comment]
Hey @sk1418 ,

Looks like the issue you were facing was due to the `node-sass` library. The version that was used doesn't seem to work with the latest versions of node. I have replaced it with `sass` which doesn't face the same issue.

I have updated the README with instructions to install and run the app locally, also I have containerized the app with docker to make it easier to self host.

Thanks for creating this issue. I wasn't aware people were using this app so I hadn't updated the README with instructions. I hope this helps.

**Comment by sk1418** [comment]
Hey @D3vd ,
thanks for the quick response!
The gif animation looks amazing, and I definitely want to  give it a try.

After a new pull and following your instruction, `yarn` doesn't complain anymore, though there were some warnings.

However, when I started the app by `yarn start` or `npm start` it logs some error messages, I paste below. (I've already installed dependencies by yarn or npm install)

Probably, it's just silly problems for js beginners. Please shed some light. Thank you.

	Failed to compile.

	./node_modules/react-dev-utils/webpackHotDevClient.js
	Error: [BABEL] /tmp/test/Clips/node_modules/react-dev-utils/webpackHotDevClient.js: Cannot find module '@babel/helper-skip-transparent-expression-wrappers'
	Require stack:
	- /tmp/test/Clips/node_modules/babel-preset-react-app/node_modules/@babel/preset-env/node_modules/@babel/plugin-proposal-optional-chaining/lib/index.js
	- /tmp/test/Clips/node_modules/babel-preset-react-app/node_modules/@babel/preset-env/lib/available-plugins.js
	- /tmp/test/Clips/node_modules/babel-preset-react-app/node_modules/@babel/preset-env/lib/plugins-compat-data.js
	- /tmp/test/Clips/node_modules/babel-preset-react-app/node_modules/@babel/preset-env/lib/normalize-options.js
	- /tmp/test/Clips/node_modules/babel-preset-react-app/node_modules/@babel/preset-env/lib/index.js

**Comment by sk1418** [comment]
BTW, when I start with docker, the app is working

**Comment by D3vd** [comment]
Hmmm. Can you try deleting your node_modules folder and then running yarn?
This could happen if you have run npm install and yarn on the same project...

**Comment by sk1418** [comment]
> Hmmm. Can you try deleting your node_modules folder and then running yarn?
> This could happen if you have run npm install and yarn on the same project...

it works. thank you.
